/**
 * Script Validator — AST-level security sandboxing for generated code.
 *
 * Provides static analysis and security validation for:
 * - Manim scripts generated by the LLM (prevents dangerous imports/calls)
 * - User code before execution (optional pre-run checks)
 *
 * Security model:
 * - ALLOWLIST: Only explicitly approved modules/objects can be used
 * - BLOCKLIST: Known dangerous patterns are explicitly blocked
 * - AST-level: Validates at the structural level, not just string matching
 */

const ALLOWED_PYTHON_IMPORTS = new Set([
    'manim', 'math', 'numpy', 'random', 'collections',
    'itertools', 'functools', 'string', 'typing', 'enum',
    'dataclasses', 'copy', 'decimal', 'fractions'
]);

const BLOCKED_PYTHON_IMPORTS = new Set([
    'os', 'sys', 'subprocess', 'shutil', 'pathlib',
    'socket', 'http', 'urllib', 'requests', 'ftplib',
    'smtplib', 'ctypes', 'multiprocessing', 'threading',
    'signal', 'pickle', 'shelve', 'marshal', 'importlib',
    'builtins', '__builtin__', 'code', 'codeop', 'compile',
    'compileall', 'py_compile', 'eval', 'exec'
]);

const BLOCKED_MANIM_OBJECTS = [
    { pattern: /MathTex\s*\(/g, name: 'MathTex', reason: 'Requires LaTeX installation' },
    { pattern: /(?<!#.*)(?<!Text)\bTex\s*\(/g, name: 'Tex', reason: 'Requires LaTeX installation' },
    { pattern: /\bCode\s*\(/g, name: 'Code', reason: 'Requires Pygments font rendering' },
    { pattern: /SVGMobject\s*\(/g, name: 'SVGMobject', reason: 'Requires external SVG files' },
    { pattern: /ImageMobject\s*\(/g, name: 'ImageMobject', reason: 'Requires external image files' },
    { pattern: /NumberPlane\s*\(/g, name: 'NumberPlane', reason: 'Complex object, often fails' },
    { pattern: /(?<!#.*)\bAxes\s*\(/g, name: 'Axes', reason: 'Complex object, often fails' },
    { pattern: /\bBrace\s*\(/g, name: 'Brace', reason: 'Uses LaTeX internally' },
    { pattern: /BraceBetweenPoints\s*\(/g, name: 'BraceBetweenPoints', reason: 'Uses LaTeX internally' },
    { pattern: /\bTable\s*\(/g, name: 'Table', reason: 'Complex rendering, use Rectangle+Text instead' },
];

const DANGEROUS_PATTERNS = [
    { pattern: /eval\s*\(/g, name: 'eval()', severity: 'critical' },
    { pattern: /exec\s*\(/g, name: 'exec()', severity: 'critical' },
    { pattern: /compile\s*\(/g, name: 'compile()', severity: 'critical' },
    { pattern: /__import__\s*\(/g, name: '__import__()', severity: 'critical' },
    { pattern: /open\s*\([^)]*,\s*['"]w/g, name: 'open() in write mode', severity: 'high' },
    { pattern: /subprocess\./g, name: 'subprocess module', severity: 'critical' },
    { pattern: /os\.(system|popen|exec|spawn)/g, name: 'os shell execution', severity: 'critical' },
    { pattern: /shutil\.(rmtree|move|copy)/g, name: 'shutil file operations', severity: 'high' },
];

/**
 * Strip comments and string literals from Python code for accurate analysis.
 * @param {string} code - Raw Python source code
 * @returns {string} Code with comments and strings removed
 */
function stripCommentsAndStrings(code) {
    return code
        .replace(/#.*$/gm, '')           // Single-line comments
        .replace(/"""[\s\S]*?"""/g, '')   // Triple-double-quote strings
        .replace(/'''[\s\S]*?'''/g, '')   // Triple-single-quote strings
        .replace(/"[^"\n]*"/g, '""')      // Collapse double-quote strings
        .replace(/'[^'\n]*'/g, "''");     // Collapse single-quote strings
}

/**
 * Extract import statements from Python code.
 * @param {string} code - Python source code
 * @returns {string[]} Array of imported module names
 */
function extractImports(code) {
    const imports = [];
    const stripped = stripCommentsAndStrings(code);

    // Match: import X, from X import Y
    const importRegex = /^(?:from\s+(\S+)\s+import|import\s+(\S+))/gm;
    let match;
    while ((match = importRegex.exec(stripped)) !== null) {
        const moduleName = (match[1] || match[2]).split('.')[0];
        imports.push(moduleName);
    }

    return imports;
}

/**
 * Validate that a Python script only uses allowed imports.
 * @param {string} code - Python source code
 * @returns {{ safe: boolean, violations: Array<{module: string, severity: string}> }}
 */
function validateImports(code) {
    const imports = extractImports(code);
    const violations = [];

    for (const mod of imports) {
        if (BLOCKED_PYTHON_IMPORTS.has(mod)) {
            violations.push({ module: mod, severity: 'critical', reason: `Blocked module: ${mod}` });
        } else if (!ALLOWED_PYTHON_IMPORTS.has(mod)) {
            violations.push({ module: mod, severity: 'warning', reason: `Unknown module: ${mod} (not in allowlist)` });
        }
    }

    return { safe: violations.filter(v => v.severity === 'critical').length === 0, violations };
}

/**
 * Validate a Manim script for safety and correctness.
 * Checks: banned objects, dangerous patterns, import safety, animation structure.
 * @param {string} script - Manim Python script
 * @returns {{ safe: boolean, errors: string[], warnings: string[] }}
 */
function validateManimScript(script) {
    const errors = [];
    const warnings = [];
    const stripped = stripCommentsAndStrings(script);

    // 1. Check imports
    const importResult = validateImports(script);
    for (const v of importResult.violations) {
        if (v.severity === 'critical') errors.push(v.reason);
        else warnings.push(v.reason);
    }

    // 2. Check for dangerous execution patterns
    for (const { pattern, name, severity } of DANGEROUS_PATTERNS) {
        pattern.lastIndex = 0;
        if (pattern.test(stripped)) {
            if (severity === 'critical') errors.push(`Dangerous call: ${name}`);
            else warnings.push(`Potentially unsafe: ${name}`);
        }
    }

    // 3. Check for banned Manim objects
    for (const { pattern, name, reason } of BLOCKED_MANIM_OBJECTS) {
        pattern.lastIndex = 0;
        if (pattern.test(stripped)) {
            errors.push(`Banned Manim object: ${name} — ${reason}`);
        }
    }

    // 4. Verify construct() method exists
    if (!script.includes('def construct(self')) {
        errors.push('Missing construct(self) method');
    }

    // 5. Check animation structure
    const playCount = (stripped.match(/self\.play\s*\(/g) || []).length;
    const waitCount = (stripped.match(/self\.wait\s*\(/g) || []).length;
    const addCount = (stripped.match(/self\.add\s*\(/g) || []).length;

    if (playCount === 0 && waitCount === 0) {
        errors.push('No self.play() or self.wait() calls — video will have zero duration');
    }
    if (playCount === 0 && addCount > 0) {
        errors.push('Only self.add() without self.play() — no animation timeline');
    }
    if (playCount < 5) {
        warnings.push(`Only ${playCount} self.play() call(s) — minimum 5 recommended`);
    }

    return {
        safe: errors.length === 0,
        errors,
        warnings,
        stats: { playCount, waitCount, addCount }
    };
}

/**
 * Quick safety check for any code before execution.
 * @param {string} code - Source code
 * @param {string} language - Language identifier
 * @returns {{ safe: boolean, reason: string }}
 */
function quickSafetyCheck(code, language) {
    // For now, only Python scripts get deep validation
    if (['python', 'py'].includes(language)) {
        const result = validateImports(code);
        if (!result.safe) {
            return { safe: false, reason: result.violations.map(v => v.reason).join('; ') };
        }
    }
    return { safe: true, reason: '' };
}

module.exports = {
    validateManimScript,
    validateImports,
    quickSafetyCheck,
    extractImports,
    stripCommentsAndStrings,
    ALLOWED_PYTHON_IMPORTS,
    BLOCKED_PYTHON_IMPORTS,
    BLOCKED_MANIM_OBJECTS,
};
